### ISSUE TITLE
Default admin account doesn't work using the provided db.sql dump

### ISSUE THREAD

**Issue by fibasile** [openp2pdesign/FabDrupal#3]
As per subject, I couldn't login using the default admin user, admin password pair when loading the provided db.sql instead of using install.php

**Comment by openp2pdesign** [comment]
I exported again the db, it now works on my computer, try with the db.sql from commit b20866074a47edaaa01dbe78796d8bee7186d2a5

**Comment by openp2pdesign** [comment]
I've moved the db.sql from the repository to save space, you can find it here now:
[https://www.dropbox.com/s/dw818gfddjqjjgs/db.sql](https://www.dropbox.com/s/dw818gfddjqjjgs/db.sql)
