### ISSUE TITLE
Install of version 2 fails when setting up profiles

### ISSUE THREAD

**Issue by fibasile** [openp2pdesign/FabDrupal#7]
An AJAX HTTP error occurred. HTTP Result Code: 200 Debugging information follows. Path: http://54.194.98.38/install.php?profile=fabdrupal&locale=en&id=1&op=do StatusText: OK ResponseText: Home | Drupal @import url("http://54.194.98.38/modules/system/system.messages.css?0"); @import url("http://54.194.98.38/modules/system/system.base.css?0"); @import url("http://54.194.98.38/modules/system/system.theme.css?0"); @import url("http://54.194.98.38/modules/system/system.menus.css?0"); @import url("http://54.194.98.38/modules/aggregator/aggregator.css?0"); @import url("http://54.194.98.38/sites/all/modules/calendar/css/calendar_multiday.css?0"); @import url("http://54.194.98.38/modules/comment/comment.css?0"); @import url("http://54.194.98.38/sites/all/modules/date/date_api/date.css?0"); @import url("http://54.194.98.38/modules/field/theme/field.css?0"); @import url("http://54.194.98.38/modules/node/node.css?0"); @import url("http://54.194.98.38/modules/user/user.css?0"); @import url("http://54.194.98.38/sites/all/modules/views/css/views.css?0"); @import url("http://54.194.98.38/modules/system/system.admin.css?0"); @import url("http://54.194.98.38/modules/system/system.maintenance.css?0"); @import url("http://54.194.98.38/sites/all/modules/ckeditor/ckeditor.css?0"); @import url("http://54.194.98.38/sites/all/modules/ctools/css/ctools.css?0"); @import url("http://54.194.98.38/themes/seven/reset.css?0"); @import url("http://54.194.98.38/themes/seven/style.css?0"); Home Installation tasksChoose profile(done)Choose language(done)Verify requirements(done)Set up database(done)Install profile(active)Configure siteMachine reservationFinished Attempt to create a field of unknown type image.

**Comment by openp2pdesign** [comment]
Yes, it happened to me as well, just reload the page and everything works well.
I will try to fix it asap.

**Comment by openp2pdesign** [comment]
This may be a possible solution: 
http://computerhelperzz.blogspot.it/2013/08/drupal-commerce-commerce-kit-error.html

**Comment by openp2pdesign** [comment]
... this seems to be the problem: "Attempt to create a field of unknown type image."

**Comment by openp2pdesign** [comment]
I fixed that error, but now getting "Attempt to create a field of unknown type taxonomy_term_reference."

**Comment by openp2pdesign** [comment]
Ok, it was probably an error during the creation of the package, I created it manually and now it seems to work with [v0.21](https://github.com/OpenP2PDesignOrg/FabDrupal/releases/tag/v0.21). Please have a look and let me know!
